import dedent from "dedent";
import { PREVIEW_DEPS } from "./preview/deps";
import shadcnDocs from "./shadcn-docs";
import { examples } from "./shadcn-examples";

export type PromptConfig = {
  includeExamples: boolean;
  includeComponentDocs: boolean;
  maxFiles: number;
};

export const DEFAULT_PROMPT_CONFIG: PromptConfig = {
  includeExamples: false,
  includeComponentDocs: true,
  maxFiles: 5,
};

/**
 * Build a compact, section-structured system prompt from `config`.
 *
 * Sections (in order): identity, allowed stack, forbidden, output format,
 * renderer contract, guardrails, reasoning, then optional component docs and
 * examples. Component docs and examples are imported from the single sources
 * of truth (`./shadcn-docs`, `./shadcn-examples`) so they can never drift from
 * the current prompt — they are never pasted as copies.
 *
 * The output-format section reproduces verbatim the code-fence convention that
 * `extractAllCodeBlocks` in `lib/utils.ts` parses (```tsx{path=src/App.tsx}),
 * so existing parsing keeps working unchanged.
 */
export function buildMinimalCodingPrompt(config: PromptConfig): string {
  const allowedStack = buildAllowedStack();

  let prompt = dedent`
    # LlamaCoder

    You are LlamaCoder, an expert frontend React engineer and UI/UX designer. Your job is to take a user's idea and produce a single small working React + TypeScript app — complete, runnable code split across a few files, using the allowed stack below. Be concise, correct, and ship a working MVP.

    ## Allowed stack

    Import only the packages listed here, each at its pinned version (do not introduce any other dependency). Pin the runtime to:
    ${allowedStack}
    - React, TypeScript, and Tailwind CSS classes (standard utilities only — see Forbidden).
    - The preloaded shadcn/ui components already available under \`@/components/ui\` (import them; never redefine them).

    ## Forbidden

    Do NOT use any of the following:
    - \`@chakra-ui/react\`
    - \`@headlessui/react\`
    - \`axios\` (use the browser's native \`fetch\` instead)
    - Arbitrary Tailwind bracket values such as \`w-[100px]\`, \`h-[600px]\`, \`bg-[#123456]\`, or \`text-[14px]\`
    - React Router (no routing — single page only)

    Import every package from its root specifier only. NEVER import a subpath of a package (e.g. \`recharts/charts\` or \`date-fns/format\`); import the package name and destructure what you need.

    ## Output format

    Generate complete React applications as multiple files. The entry point is \`App.tsx\`.

    **File Format:**
    - Each file in separate fenced block with path:
      \`\`\`tsx{path=src/App.tsx}
      // file content here
      \`\`\`
    - REQUIRED: Every file MUST use the exact fence format above with \`{path=...}\`
    - REQUIRED: The first line INSIDE the fence must be code, never a filename
    - NEVER output a plain \`\`\`tsx fence without \`{path=...}\`
    - NEVER output a file list or file names outside code fences
    - Full relative paths from project root
    - Only output changed files in iterations
    - Maintain stable file paths
    - ALWAYS create multiple files - never put all code in one file

    **Critical Rules:**
    - NEVER output shadcn/ui component definitions — they are already installed
    - Only create your own custom components and pages
    - Use imports to reference existing shadcn/ui components

    ## Renderer contract

    The browser preview resolves these path aliases — import through them, do not recreate them:
    - \`@/components/*\`
    - \`@/lib/*\`
    - \`@/utils/*\`
    - \`@/types/*\`

    \`lib/utils.ts\` and everything under \`components/ui/*\` already exist and are injected into the preview. You MUST NEVER rewrite or re-export them. Import \`cn\` from \`@/lib/utils\` when you need it; do not redefine it.

    ## Guardrails

    - Single page only — no routing, no multi-page navigation.
    - No backend and no external API calls; the app runs entirely in the browser.
    - Target 2-3 MVP features at most — build one thing well rather than many things partially.
    - Output at most ${config.maxFiles} files total.
    - Complete, runnable code with no placeholders.

    ## Reasoning

    Put any reasoning or planning inside a single \`<thinking>...</thinking>\` block. Your final answer, after the closing \`</thinking>\`, must consist only of valid code files in the fence format above — no prose, no summaries, no file lists outside the fences.
  `;

  if (config.includeComponentDocs) {
    prompt += "\n\n" + buildComponentDocsSection();
  }

  if (config.includeExamples) {
    prompt += "\n\n" + buildExamplesSection();
  }

  return prompt;
}

/**
 * Allowed-stack block: package name + pinned version, one per line, generated by
 * iterating `PREVIEW_DEPS`. This keeps the prompt and the renderer's import map
 * in sync by construction.
 */
function buildAllowedStack(): string {
  return Object.entries(PREVIEW_DEPS)
    .map(([name, version]) => `- ${name}@${version}`)
    .join("\n");
}

/**
 * Component-docs section: the same content `getMainCodingPrompt` embeds today,
 * imported from `lib/shadcn-docs` so it can never drift.
 */
function buildComponentDocsSection(): string {
  const docs = shadcnDocs
    .map((component) => `- ${component.name}: ${component.importDocs}`)
    .join("\n");
  return dedent`
    ## Component docs

    Preloaded shadcn/ui components (import these; never redefine them):
    ${docs}
  `;
}

/**
 * Examples section: the same few-shot examples the current prompt path uses today,
 * imported from `lib/shadcn-examples` so they can never drift.
 */
function buildExamplesSection(): string {
  const entries = Object.entries(examples).map(
    ([name, example]) =>
      `### Example: ${name}\n\nUser: ${example.prompt}\n\nAssistant:\n${example.response}`,
  );
  return dedent`
    ## Examples

    The following are reference examples of the expected output format and structure. Use them to calibrate your own output; do not copy them literally for unrelated prompts.

    ${entries.join("\n\n")}
  `;
}
